Protected virtual processprefab
SubnauticaModding/SMLHelper pull request #225
Opened 2021-06-21 21:46 UTC by LeeTwentyThree

### Changes made in this pull request

  - Make processprefab protected virtual and add docs

2021-06-21 21:49 UTC, Metious approved these changes

2021-06-24 17:12 UTC, tobeyStraitjacket requested changes

2021-06-24 17:12 UTC, tobeyStraitjacket commented on SMLHelper/Assets/ModPrefab.cs
> +        /// </summary>
```suggestion
        /// <summary>
        /// Caches the prefab, then sets its TechType and ClassID to a default set of values applicable to most mods.<br/>
        /// FOR ADVANCED MODDING ONLY. Do not override unless you know exactly what you are doing.
        /// </summary>
```

2021-06-26 13:58 UTC, tobeyStraitjacket approved these changes

2021-07-04 21:28 UTC, merged