added MakeEatable method and pickupable patch
SubnauticaModding/SMLHelper pull request #276
Opened 2022-09-11 23:44 UTC by Nagorogan

pickupable patch only gets patched if at least one edible is added, and it takes over the original eatable patch if so. No need to have two patches there when one would do, right?

mostly so that CC2 can allow for items to be made edible solely through smlhelper.

2022-09-12 10:01 UTC, Metious commented on SMLHelper/Interfaces/IEatableHandler.cs
> +        void MakeEatable(TechType item, float food, float water, bool decomposes = true);
Make it more descriptive and accurate (edit -> add, etc..)

2022-09-12 10:01 UTC, Metious commented on SMLHelper/Interfaces/IEatableHandler.cs
> +        void MakeEatable(TechType item, float food, float water, bool decomposes = true, float health = 0f, float coldValue = 0f, int maxCharges = 0);
Make the doc more descriptive and accurate (edit -> add, etc..)

2022-09-12 11:08 UTC, PrimeSonic commented on SMLHelper/Initializer.cs
> +                EatablePatcher.Patch(harmony);
That else shouldn't be there.
It's only the pickup able patcher that needs to be skipped.

2022-11-19 08:43 UTC, Metious requested changes

2022-11-19 08:43 UTC, Metious commented on SMLHelper/Handlers/EatableHandler.cs
> +        private static bool pickupablePatched = false;
Looks like this is never assigned. Move it to the patcher and set it to `true` after patching.
The handler should only call `PickupablePatcher.Patch` and have no business in determining if it's patched yet or not.

2023-04-18 17:57 UTC, closed without merging