Added basic color picker
SubnauticaModding/SMLHelper pull request #295
Opened 2023-01-10 21:22 UTC by JKohlman

### Changes made in this pull request

  - Added a basic color picker and storage for a `Color` in config

TODO:
- [ ] Add a more advanced version with sliders below (based on Purple's Vector3 BepInEx config conversion)

2023-01-11 03:28 UTC, JKohlman commented
Should be good to go for testing/review!

2023-01-11 16:25 UTC, MrPurple6411 requested changes

2023-01-11 16:25 UTC, MrPurple6411 commented on SMLHelper/Options/ModColorOption.cs
> +                    }),
Please add the Alpha Slider as well.
If you want let me know and I will do it.

2023-01-11 16:25 UTC, MrPurple6411 commented on SMLHelper/Options/ModColorOption.cs
> +    public class ModColorOption : ModOption<Color, ColorChangedEventArgs>
Can we get a Bepinex Config Entry conversion extension added.
If you want let me know and I will do it.

2023-01-13 08:57 UTC, MrPurple6411 approved these changes

2023-01-13 08:57 UTC, merged